# Generated by Django 5.1 on 2024-08-21 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('chave_jogo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Desenvolvedora', models.CharField(max_length=255)),
                ('Versão', models.IntegerField()),
                ('Categoria', models.CharField(max_length=255)),
                ('Média_Avaliações', models.IntegerField()),
                ('Média_Horas_Jogando', models.IntegerField()),
            ],
        ),
    ]
