# Generated by Django 5.1 on 2024-08-23 17:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('chave_jogo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Desenvolvedora', models.CharField(max_length=255)),
                ('Versão', models.CharField(max_length=255)),
                ('Categoria', models.CharField(max_length=255)),
                ('Média_Avaliações', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Média_Horas_Jogando', models.CharField(max_length=255)),
            ],
        ),
    ]
