# Generated by Django 5.1 on 2024-08-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='Média_Avaliações',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='Média_Horas_Jogando',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='Versão',
            field=models.CharField(max_length=255),
        ),
    ]
