# Generated by Django 5.1 on 2024-08-21 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_jogos_média_horas_jogando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='Média_Horas_Jogando',
            field=models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
