# Generated by Django 5.1 on 2024-08-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
